create table t_repos
(
    id                   int auto_increment comment 'repo_id'
        primary key,
    repo_name            varchar(256) default 'repo_name'  not null,
    github_url           varchar(256) default 'github_url' not null,
    owner                varchar(128) default 'owner'      not null comment 'owner of repo',
    name                 varchar(128) default 'name'       not null comment 'name of repo',
    is_searched          int          default 0            not null comment '0 stands for searched repos of input topics',
    is_filtered_keywords int          default 0            null comment '1 filter out, 0 means that repo not related to the keywords about leetcode/algorithm',
    has_downloaded       int          default 0            not null comment '0 undownloaded,1 downloaded',
    is_contained_depen   int          default 0            not null comment '0 not contain aimed dependencies 1 contained',
    constraint index1
        unique (id)
);

INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (1, 'wordpress-mobile/WordPress-Android', 'https://github.com/wordpress-mobile/WordPress-Android', 'wordpress-mobile', 'WordPress-Android', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (2, 'nextcloud/android', 'https://github.com/nextcloud/android', 'nextcloud', 'android', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (3, 'element-hq/element-android', 'https://github.com/element-hq/element-android', 'element-hq', 'element-android', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (4, 'thunderbird/thunderbird-android', 'https://github.com/thunderbird/thunderbird-android', 'thunderbird-android', 'thunderbird-android', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (5, 'pockethub/PocketHub', 'https://github.com/pockethub/PocketHub', 'pockethub', 'PocketHub', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (6, 'supertokens/supertokens-core', 'https://github.com/supertokens/supertokens-core', 'supertokens', 'supertokens-core', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (7, 'TeamAmaze/AmazeFileManager', 'https://github.com/TeamAmaze/AmazeFileManager', 'TeamAmaze', 'AmazeFileManager', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (8, 'firebase/FirebaseUI-Android', 'https://github.com/firebase/FirebaseUI-Android', 'firebase', 'FirebaseUI-Android', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (9, 'owncloud/android', 'https://github.com/owncloud/android', 'owncloud', 'android', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (10, 'duckduckgo/Android', 'https://github.com/duckduckgo/Android', 'duckduckgo', 'Android', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (11, 'TwidereProject/Twidere-Android', 'https://github.com/TwidereProject/Twidere-Android', 'TwidereProject', 'Twidere-Android', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (12, 'fossasia/phimpme-android', 'https://github.com/fossasia/phimpme-android', 'fossasia', 'phimpme-android', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (13, 'orgzly/orgzly-android', 'https://github.com/orgzly/orgzly-android', 'orgzly', 'orgzly-android', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (14, 'android-password-store/Android-Password-Store', 'https://github.com/android-password-store/Android-Password-Store', 'android-password-store', 'Android-Password-Store', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (15, 'Automattic/pocket-casts-android', 'https://github.com/Automattic/pocket-casts-android', 'Automattic', 'pocket-casts-android', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (16, 'connectbot/connectbot', 'https://github.com/connectbot/connectbot', 'connectbot', 'connectbot', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (17, 'realm/realm-java', 'https://github.com/realm/realm-java', 'realm', 'realm-java', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (18, 'firebase/quickstart-android', 'https://github.com/firebase/quickstart-android', 'firebase', 'quickstart-android', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (19, 'ankidroid/Anki-Android', 'https://github.com/ankidroid/Anki-Android', 'ankidroid', 'Anki-Android', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (20, 'libre-tube/LibreTube', 'https://github.com/libre-tube/LibreTube', 'libre-tube', 'LibreTube', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (21, 'beemdevelopment/Aegis', 'https://github.com/beemdevelopment/Aegis', 'beemdevelopment', 'Aegis', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (22, 'microg/GmsCore', 'https://github.com/microg/GmsCore', 'microg', 'GmsCore', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (23, 'facebook/facebook-android-sdk', 'https://github.com/facebook/facebook-android-sdk', 'facebook', 'facebook-android-sdk', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (24, 'kickstarter/android-oss', 'https://github.com/kickstarter/android-oss', 'kickstarter', 'android-oss', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (25, 'AntennaPod/AntennaPod', 'https://github.com/AntennaPod/AntennaPod', 'AntennaPod', 'AntennaPod', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (26, 'recloudstream/cloudstream', 'https://github.com/recloudstream/cloudstream', 'recloudstream', 'cloudstream', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (27, 'PhilippC/keepass2android', 'https://github.com/PhilippC/keepass2android', 'PhilippC', 'keepass2android', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (28, 'Docile-Alligator/Infinity-For-Reddit', 'https://github.com/Docile-Alligator/Infinity-For-Reddit', 'Docile-Alligator', 'Infinity-For-Reddit', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (29, 'react-native-google-signin/google-signin', 'https://github.com/react-native-google-signin/google-signin', 'react-native-google-signin', 'google-signin', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (30, 'fossasia/phimpme-android', 'https://github.com/fossasia/phimpme-android', 'fossasia', 'phimpme-android', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (31, 'tuskyapp/Tusky', 'https://github.com/tuskyapp/Tusky', 'tuskyapp', 'Tusky', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (32, 'fossasia/open-event-attendee-android', 'https://github.com/fossasia/open-event-attendee-android', 'fossasia', 'open-event-attendee-android', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (33, 'parse-community/Parse-SDK-Android', 'https://github.com/parse-community/Parse-SDK-Android', 'parse-community', 'Parse-SDK-Android', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (34, 'home-assistant/android', 'https://github.com/home-assistant/android', 'home-assistant', 'android', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (35, 'jellyfin/jellyfin-android', 'https://github.com/jellyfin/jellyfin-android', 'jellyfin', 'jellyfin-android', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (36, 'bitfireAT/davx5-ose', 'https://github.com/bitfireAT/davx5-ose', 'bitfireAT', 'davx5-ose', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (37, 'commons-app/apps-android-commons', 'https://github.com/commons-app/apps-android-commons', 'commons-app', 'apps-android-commons', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (38, 'element-hq/element-x-android', 'https://github.com/element-hq/element-x-android', 'element-hq', 'element-x-android', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (39, 'wallabag/android-app', 'https://github.com/wallabag/android-app', 'wallabag', 'android-app', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (40, 'mozilla-mobile/reference-browser', 'https://github.com/mozilla-mobile/reference-browser', 'mozilla-mobile', 'reference-browser', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (41, 'tinode/tindroid', 'https://github.com/tinode/tindroid', 'tinode', 'tindroid', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (42, 'microsoft/appcenter-sdk-android', 'https://github.com/microsoft/appcenter-sdk-android', 'microsoft', 'appcenter-sdk-android', 1, 1, 1, 1);
INSERT INTO db_repos.t_repos (id, repo_name, github_url, owner, name, is_searched, is_filtered_keywords, has_downloaded, is_contained_depen) VALUES (43, 'woocommerce/woocommerce-android', 'https://github.com/woocommerce/woocommerce-android', 'woocommerce', 'woocommerce-android', 1, 1, 1, 1);
